fix: add missing hass argument to IntegrationSensor
- IntegrationSensor.__init__() requires hass as first positional argument
- Added hass parameter to EcoFlowIntegralEnergySensor.__init__()
- Updated all EcoFlowIntegralEnergySensor instantiations to pass hass
- Fixes TypeError: IntegrationSensor.__init__() missing 1 required positional argument: 'hass'